steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "europe-west1-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY_ID}/${_SERVICE_NAME}:${_TAG}", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "europe-west1-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY_ID}/${_SERVICE_NAME}:${_TAG}"]

substitutions:
  _SERVICE_NAME: "mrssanta-api"
  _REPOSITORY_ID: "mrssanta-artifacts"
  _TAG: "latest"
